server:
  port: 8083
#  ioMode: NIO
  bes:
    maxThreads: 300
    basedir: mqpass-cproxy
logging:
  file:
    path:  ./logs/connection_reset_demo_server/
    name: ${spring.application.name}.log
spring:
  application:
    name: connection-reset-demo-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 30000
  metrics:
    enable:
      jvm:
        threads: false
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        bes:
          enabled: true
          period: 4500
